#Run with: docker build -t mything:1.0 .
# Base image is the splunk/splunk image
FROM splunk/splunk 

# Next set env variables, we did the same in the docker compose also
# Probably better to do this in docker compose
ENV SPLUNK_START_ARGS=--accept-license \
    SPLUNK_PASSWORD=password

#Run a linux command in the container
# You can have many RUN commands
RUN mkdir -p /tmp/newfolder

# Copy from server to container
COPY . /tmp/newfolder

# You have 1 CMD, it runs the server, once it's done the container goes down
CMD [ "start-service"]

Going to the adventuring guild.

Go out and kill random stuff naration

Find Star Swirl the bearded (centour)
	Sulferish smell coming from him, he is an elder oblex, doubt anyone will notice
		https://dr-eigenvalue.github.io/bestiary/creature/elder-oblex
	Tells party they should find a master mage who knows gate
	Very very interested in Ovlan's place.
	Can't teleport you there directly

pre-commit
travis

Public speaking in NTC
	Try to start it
	
Slow pace
Organize thoughts
move around
talk with your hands
after you introduce yourself tell them
	Throw in something personal so they can ID with you
	Add in why they should listen, why it was importand to me
	What your going to tell them, restate it 3x times, keep it simple. 2-3 points.
give them high level, let them come to you with low level

	