# Generated by Django 3.2 on 2021-06-01 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='totorial_title',
            new_name='tutorial_title',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 12, 43, 6, 525213), verbose_name='date published'),
        ),
    ]
